color: null
fieldLayouts:
  6c21a4e1-876d-4aea-8414-e4be48f8c534:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T01:41:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Artist name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec2574d9-851b-4eae-aeb3-455d40e3d706
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T01:47:17+00:00'
            elementCondition: null
            fieldUid: 2087286d-55f6-4e01-845c-963925c89ed0 # First name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8b84a49-0d08-48b9-98ef-321507ceccd0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T01:47:17+00:00'
            elementCondition: null
            fieldUid: 98c629b7-3c4b-4e2e-b8ab-445a4a4fa830 # Last name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4c8b21-9d8a-4c63-a226-95939f569e52
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T01:47:17+00:00'
            elementCondition: null
            fieldUid: 4b893952-6d87-41c4-b19e-981785c6a9dc # Country
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 172812aa-a12b-499c-987e-ca59d5c9451e
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: b3a6ce71-6f16-4850-9db0-ce1bb0574f78
        userCondition: null
handle: artists
hasTitleField: true
icon: ''
name: Artists
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
