headingLevels:
  - 1
  - 2
  - 3
name: Simple
toolbar:
  - heading
  - '|'
  - bold
  - underline
  - italic
  - link
  - subscript
  - superscript
  - bulletedList
  - numberedList
  - todoList
  - horizontalLine
  - insertTable
  - blockQuote
  - sourceEditing
