altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  48a40b3e-f54f-4865-8267-f20576912657:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T12:20:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0ae6198c-a2a1-4408-9e74-24ea2da6d00d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-10-31T12:40:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 799f789a-af8f-4c72-9706-c1e9ab1511e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T12:40:35+00:00'
            elementCondition: null
            fieldUid: 0672edec-34b9-46f5-b93d-cccb912b32f7 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffbe0e2f-cab1-4b8e-86ad-c4c550ef0181
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: e925a30e-365e-4b15-b1ae-d85062dca26b
        userCondition: null
fs: images
handle: uploads
name: Uploads
sortOrder: 1
subpath: '%UPLOADS_SUBPATH_PRODUCTS_IMAGES%'
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: '%TRANSOFRM_SUBPATH_PRODUCTS_IMAGES%'
