columnSuffix: null
handle: description
instructions: null
name: description
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: cd6e6a1f-8874-419e-9f8d-7f2556ea12a1 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
