columnSuffix: null
handle: duration
instructions: null
name: Duration
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'mm:ss'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
