defaultPlacement: end
enableVersioning: true
entryTypes:
  - ba95ab94-907b-4e9c-9217-65ace999d23c # Artists
handle: artists
maxAuthors: 1
name: Artists
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7ba4af42-140a-4814-a0c1-2466f2442902: # High Bass Audio
    enabledByDefault: true
    hasUrls: true
    template: artists/_entry.twig
    uriFormat: 'artists/{slug}'
type: channel
